version: '3'

services:
  app:
    container_name: api-messenger
    restart: always
    build: .
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - MONGODB_URI=mongodb://mongo/messenger
      - SPRING_DATA_MONGODB_HOST=mongo
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    container_name: mongo-messenger-db
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: "messenger"
    volumes:
      - ./mongoVolume:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge