server:
  port: 8080
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      authentication-database: admin
      database: messenger
      port: 27017
  servlet:
    multipart:
      enabled: true
      file-size-threshold: ${FILE_SIZE_THRESHOLD:2MB}
      max-file-size: ${MAX_FILE_SIZE:1GB}
      max-request-size: ${MAX_REQUEST_SIZE:1GB}
logging:
  level:
    org:
      springframework: ERROR
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.sss} [%thread] %-5level %logger{36}: %msg%n"
  file:
    name: logs/pechkin.log
    path: logs/