server:
  port: 8080
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      authentication-database: admin
      database: messenger
      port: 27017
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 1GB
      max-request-size: 1GB
cloud:
  aws:
    credentials:
      accessKey: vQJ1SbOjLtIBSnFyG8yA
      secretKey: AZpH9VA22Y38JaNcv0qWNCXenUVU49Im3lYr3zLp
    region:
      static: us-east-1
logging:
  level:
    org:
      springframework: ERROR
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.sss} [%thread] %-5level %logger{36}: %msg%n"
  file:
    name: logs/pechkin.log
    path: logs/